global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'melwin96@yahoo.com'
    from: 'vinublaze123@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'vinublaze123@gmail.com'
    auth_identity: 'vinublaze123@gmail.com'
    auth_password: 'gyoabddeydypxzsj'